INSERT INTO users (username, password, role) VALUES ('admin1', '$2a$10$o2rgu2CCsZYD9U8VDzT95OTRNA8dXf3rDd00QbZO8Y0HI2utneCTO', 'ADMIN');
INSERT INTO users (username, password, role) VALUES ('user1', '$2a$10$o2rgu2CCsZYD9U8VDzT95OTRNA8dXf3rDd00QbZO8Y0HI2utneCTO', 'USER');

INSERT INTO contents (title, description, view_count, created_date, created_by, last_modified_date, last_modified_by, deleted) VALUES
                                                                                                                          ('테스트 게시글 01', '테스트 내용 01입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 02', '테스트 내용 02입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 03', '테스트 내용 03입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 04', '테스트 내용 04입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 05', '테스트 내용 05입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 06', '테스트 내용 06입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 07', '테스트 내용 07입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 08', '테스트 내용 08입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 09', '테스트 내용 09입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 10', '테스트 내용 10입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 11', '테스트 내용 11입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 12', '테스트 내용 12입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 13', '테스트 내용 13입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 14', '테스트 내용 14입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 15', '테스트 내용 15입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 16', '테스트 내용 16입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 17', '테스트 내용 17입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 18', '테스트 내용 18입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 19', '테스트 내용 19입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false),
                                                                                                                          ('테스트 게시글 20', '테스트 내용 20입니다.', 0, CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1', false);