CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50) NOT NULL UNIQUE,
                       password VARCHAR(100) NOT NULL,
                       role VARCHAR(20) NOT NULL
);

CREATE TABLE contents (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          title VARCHAR(100) NOT NULL,
                          description CLOB,
                          view_count BIGINT NOT NULL DEFAULT 0,
                          created_date TIMESTAMP,
                          created_by VARCHAR(50) NOT NULL,
                          last_modified_date TIMESTAMP,
                          last_modified_by VARCHAR(50),
                          deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE comments (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         text VARCHAR(500) NOT NULL,
                         created_date TIMESTAMP,
                         created_by VARCHAR(50) NOT NULL,
                         last_modified_date TIMESTAMP,
                         content_id BIGINT NOT NULL,
                         deleted BOOLEAN NOT NULL DEFAULT FALSE,
                         CONSTRAINT fk_comments_contents FOREIGN KEY (content_id) REFERENCES contents (id)
);

CREATE TABLE attachments (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            original_file_name VARCHAR(300) NOT NULL,
                            store_file_name VARCHAR(255) NOT NULL,
                            file_path VARCHAR(500) NOT NULL,
                            file_size BIGINT,
                            content_type VARCHAR(255),
                            content_id BIGINT NOT NULL,
                            CONSTRAINT fk_attachments_contents FOREIGN KEY (content_id) REFERENCES contents (id)
);